variables:
  REGISTRY_HOST: hub.irontec.com

stages:
  - build

before_script:
- docker info
- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_HOST

build:7.4:
  stage: build
  tags:
    - docker
    - runners
  script:
    - docker build --no-cache --build-arg PHP_VERSION=7.4-fpm-buster -t $REGISTRY_HOST/$CI_PROJECT_PATH/7.4:$CI_BUILD_REF -t $REGISTRY_HOST/$CI_PROJECT_PATH/7.4:latest .
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/7.4:$CI_BUILD_REF
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/7.4:latest

build:7.3.28:
  stage: build
  tags:
    - docker
    - runners
  script:
    - docker build --no-cache --build-arg PHP_VERSION=7.3.28-fpm-buster -t $REGISTRY_HOST/$CI_PROJECT_PATH/7.3.28:$CI_BUILD_REF -t $REGISTRY_HOST/$CI_PROJECT_PATH/7.3.28:latest .
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/7.3.28:$CI_BUILD_REF
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/7.3.28:latest

build:7.2.34:
  stage: build
  tags:
    - docker
    - runners
  script:
    - docker build --no-cache --build-arg PHP_VERSION=7.2.34-fpm-buster -t $REGISTRY_HOST/$CI_PROJECT_PATH/7.2.34:$CI_BUILD_REF -t $REGISTRY_HOST/$CI_PROJECT_PATH/7.2.34:latest .
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/7.2.34:$CI_BUILD_REF
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/7.2.34:latest

build:7.1.30:
  stage: build
  tags:
    - docker
    - runners
  script:
    - docker build --no-cache --build-arg PHP_VERSION=7.1.30-fpm-buster -t $REGISTRY_HOST/$CI_PROJECT_PATH/7.1.30:$CI_BUILD_REF -t $REGISTRY_HOST/$CI_PROJECT_PATH/7.1.30:latest .
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/7.1.30:$CI_BUILD_REF
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/7.1.30:latest

#build:7.0:
#  stage: build
#  tags:
#    - docker
#    - runners
#  script:
#    - docker build --no-cache --build-arg PHP_VERSION=7.0-fpm-stretch -t $REGISTRY_HOST/$CI_PROJECT_PATH/7.0:$CI_BUILD_REF -t $REGISTRY_HOST/$CI_PROJECT_PATH/7.0:latest .
#    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/7.0:$CI_BUILD_REF
#    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/7.0:latest
