variables:
  REGISTRY_HOST: hub.irontec.com

stages:
  - build

before_script:
- docker info
- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_HOST

build:7.3.3:
  stage: build
  tags:
    - docker
    - runners
  script:
    - docker build --no-cache --build-arg PHP_VERSION=7.3.3 -t $REGISTRY_HOST/$CI_PROJECT_PATH/7.3.3:$CI_BUILD_REF -t $REGISTRY_HOST/$CI_PROJECT_PATH/7.3.3:latest .
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/7.3.3:$CI_BUILD_REF
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/7.3.3:latest

build:7.2.15:
  stage: build
  tags:
    - docker
    - runners
  script:
    - docker build --no-cache --build-arg PHP_VERSION=7.2.15 -t $REGISTRY_HOST/$CI_PROJECT_PATH/7.2.15:$CI_BUILD_REF -t $REGISTRY_HOST/$CI_PROJECT_PATH/7.2.15:latest .
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/7.2.15:$CI_BUILD_REF
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/7.2.15:latest

build:7.1.27:
  stage: build
  tags:
    - docker
    - runners
  script:
    - docker build --no-cache --build-arg PHP_VERSION=7.1.27 -t $REGISTRY_HOST/$CI_PROJECT_PATH/7.1.27:$CI_BUILD_REF -t $REGISTRY_HOST/$CI_PROJECT_PATH/7.1.27:latest .
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/7.1.27:$CI_BUILD_REF
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/7.1.27:latest

build:7.0:
  stage: build
  tags:
    - docker
    - runners
  script:
    - docker build --no-cache --build-arg PHP_VERSION=7.0 -t $REGISTRY_HOST/$CI_PROJECT_PATH/7.0:$CI_BUILD_REF -t $REGISTRY_HOST/$CI_PROJECT_PATH/7.0:latest .
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/7.0:$CI_BUILD_REF
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/7.0:latest
