#!/usr/bin/env bash

set -e

if [ ! "${DOCKER_ENV_FILE}" = "" ]; then
    export $(grep -v '^$\|^\s*\#' ${DOCKER_ENV_FILE} | xargs -0)
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- php-fpm "$@"
fi

exec "$@"
